production:
  solr:
    hostname: us-east-1.websolr.com
    port: 443
    scheme: https
    path: /solr/f013b768a4e9/


development:
  solr:
    hostname: us-east-1.websolr.com
    port: 443
    scheme: https
    path: /solr/f013b768a4e9/


test:
  solr:
    hostname: us-east-1.websolr.com
    port: 443
    scheme: https
    path: /solr/f013b768a4e9/
